name: Unzip Source Files
on: workflow_dispatch

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download and Unzip fla.zip from Release
        run: |
          curl -L -o fla.zip https://github.com/messi317/Battle-Panic/releases/download/1.0/fla.zip
          unzip -o fla.zip -d fla_files/
          rm fla.zip

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add unzipped FLA files to repository" || echo "No changes to commit"
          git push
 
